openapi: 3.0.0
info:
  title: 멘토-멘티 매칭 API
  version: 1.0.0
  description: |-
    멘토-멘티 매칭 서비스 백엔드 API 명세(OpenAPI 3.0)
    
    - JWT Bearer 인증 필요 (회원가입/로그인 제외)
    - 모든 응답은 JSON
    - 상세 예시는 Swagger UI(/api/docs)에서 확인 가능
    - OpenAPI JSON: http://localhost:8080/v3/api-docs
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /api/auth/register:
    post:
      summary: 회원가입
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, name, role]
              properties:
                email: { type: string }
                password: { type: string }
                name: { type: string }
                role: { type: string, enum: [mentor, mentee] }
                bio: { type: string }
                skills: { type: string }
      responses:
        '201': { description: 회원가입 성공 }
        '409': { description: 이미 존재하는 이메일 }
        '400': { description: 필수 항목 누락 }
  /api/auth/login:
    post:
      summary: 로그인
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200': { description: 로그인 성공 }
        '401': { description: 인증 실패 }
  /api/profile/me:
    get:
      summary: 내 프로필 조회
      tags: [Profile]
      security:
        - bearerAuth: []
      responses:
        '200': { description: 내 정보 반환 }
        '401': { description: 인증 필요 }
    put:
      summary: 내 프로필 수정
      tags: [Profile]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                bio: { type: string }
                skills: { type: string }
      responses:
        '200': { description: 수정 완료 }
        '401': { description: 인증 필요 }
  /api/profile/image:
    post:
      summary: 프로필 이미지 업로드
      tags: [Profile]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image: { type: string, format: binary }
      responses:
        '200': { description: 업로드 성공 }
        '400': { description: 파일 오류 }
        '401': { description: 인증 필요 }
  /api/profile/image/{userId}:
    get:
      summary: 프로필 이미지 조회
      tags: [Profile]
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: integer }
      responses:
        '200': { description: 이미지 반환 }
        '404': { description: 없음 }
  /api/mentors:
    get:
      summary: 멘토 목록 조회
      tags: [Mentor]
      parameters:
        - in: query
          name: q
          schema: { type: string }
          description: 이름/기술스택 키워드 검색
        - in: query
          name: sort
          schema: { type: string, enum: [name, skills] }
          description: 정렬 기준
      responses:
        '200': { description: 멘토 리스트 반환 }
  /api/match/request:
    post:
      summary: 매칭 요청 생성(멘티)
      tags: [Match]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [mentorId]
              properties:
                mentorId: { type: integer }
                message: { type: string }
      responses:
        '201': { description: 매칭 요청 완료 }
        '403': { description: 멘티만 요청 가능 }
  /api/match/mentee:
    get:
      summary: 내 매칭 요청 목록(멘티)
      tags: [Match]
      security:
        - bearerAuth: []
      responses:
        '200': { description: 매칭 목록 반환 }
        '403': { description: 멘티만 조회 가능 }
  /api/match/mentor:
    get:
      summary: 내 매칭 요청 목록(멘토)
      tags: [Match]
      security:
        - bearerAuth: []
      responses:
        '200': { description: 매칭 목록 반환 }
        '403': { description: 멘토만 조회 가능 }
  /api/match/status/{id}:
    patch:
      summary: 매칭 상태 변경(멘토)
      tags: [Match]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [status]
              properties:
                status: { type: string, enum: [accepted, rejected, cancelled] }
      responses:
        '200': { description: 상태 변경 완료 }
        '403': { description: 멘토만 변경 가능 }
        '404': { description: 요청 없음 }
